apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-backend-bakery
  name: backend-bakery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend-bakery
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/store-manager: "true"
        io.kompose.service: backend-bakery
    spec:
      containers:
        - env:
            - name: DB_CONNECTION
          image: eo-lads-rest-api-backend:latest
          name: backend-bakery
          ports:
            - containerPort: 8080
          resources: {}
          imagePullPolicy: Never
      restartPolicy: Always
status: {}
